using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     O c�digo foi gerado por uma ferramenta.
//     Vers�o de Tempo de Execu��o:4.0.30319.42000
//
//     As altera��es ao arquivo poder�o causar comportamento incorreto e ser�o perdidas se
//     o c�digo for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("CSharpJs.Test.Api")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("xnetweb")]
[assembly: AssemblyProductAttribute("CSharpJs.Test.Api")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) xnetweb 2021")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyVersionAttribute("93.0190.30.100")]
[assembly: AssemblyFileVersionAttribute("93.0190.30.100")]

